export type iDropShipperCart = {
	id: number;
	category_id: number;
	subcategory_id: number;
	brand_id: number;
	user_id: number;
	slug: string;
	name: string;
	short_description: string;
	long_description: string;
	selling_price: string;
	original_price: string;
	qty: string;
	image: string;
	status: string;
	meta_title: null;
	meta_keyword: null;
	meta_description: null;
	tags: null;
	commision_type: null;
	request: null;
	user_type: null;
	discount_type: string;
	discount_rate: string;
	rejected_details: null;
	created_at: string;
	updated_at: string;
	deleted_at: null;
	variants: null;
	selling_type: string;
	selling_details: null;
	advance_payment: number;
	single_advance_payment_type: string;
	is_connect_bulk_single: string;
	specifications: {
		specification: string;
		specification_ans: string;
	}[];
	uniqid: string;
	sku: string;
	distributor_price: null;
	alert_qty: number;
	supplier_id: number;
	warehouse_id: number;
	exp_date: string;
	barcode: null;
	warranty: string;
	is_feature: number;
	is_affiliate: number;
	discount_price: string;
	vendor_id: number;
	pre_order: string;
	discount_percentage: string;
	product_type: string;
	wc_product_id: null;
	tenant_id: string;
	tenant_name: string;
	cart_id: number;
};

export type CartCreatePayload = {
	products: Array<{
		product_id: number;
		product_qty: number;
		variant_id?: string | null;
		color?: number | null;
		size?: number | null;
		unit_id?: number | null;
	}>;
	first_name: string;
	last_name?: string;
	phone: string;
	email: string;
	city: string;
	address: string;
	note?: string;
	delivery_area_id?: number | null;
	courier_id?: number | null;
};

export type CartUpdatePayload = {
	cart_id: number;
	products?: Array<{
		product_id: number;
		product_qty: number;
		variant_id?: string | null;
		color?: number | null;
		size?: number | null;
		unit_id?: number | null;
	}>;
	first_name?: string;
	last_name?: string;
	phone?: string;
	email?: string;
	city?: string;
	address?: string;
	note?: string;
	delivery_area_id?: number | null;
	courier_id?: number | null;
};

export type iDropShipperCartView = {
	data: {
		id: number;
		user_id: number;
		product_id: number;
		product_qty: number;
		product_price: string;
		vendor_id: string;
		color: null;
		size: null;
		amount: string;
		created_at: string;
		updated_at: string;
		category_id: number;
		totalproductprice: number;
		total_affiliate_commission: number;
		purchase_type: string;
		advancepayment: number;
		totaladvancepayment: number;
		tenant_id: string;
		product: {
			id: number;
			category_id: number;
			subcategory_id: number;
			brand_id: number;
			user_id: number;
			slug: string;
			name: string;
			short_description: string;
			long_description: string;
			selling_price: string;
			original_price: string;
			qty: string;
			image: string;
			status: string;
			meta_title: null;
			meta_keyword: null;
			meta_description: null;
			tags: null;
			commision_type: null;
			request: null;
			user_type: null;
			discount_type: string;
			discount_rate: string;
			rejected_details: null;
			created_at: string;
			updated_at: string;
			deleted_at: null;
			variants: null;
			selling_type: string;
			selling_details: null;
			advance_payment: number;
			single_advance_payment_type: string;
			is_connect_bulk_single: string;
			specifications: {
				specification: string;
				specification_ans: string;
			}[];
			uniqid: string;
			sku: string;
			distributor_price: null;
			alert_qty: number;
			supplier_id: number;
			warehouse_id: number;
			exp_date: string;
			barcode: null;
			warranty: string;
			is_feature: number;
			is_affiliate: number;
			discount_price: string;
			vendor_id: number;
			pre_order: string;
			discount_percentage: string;
			product_type: string;
			wc_product_id: null;
			tenant_id: string;
			tenant_name: string;
		};
		cart_details: {
			id: number;
			cart_id: number;
			color: {
				id: number;
				name: string;
			};
			size: {
				id: number;
				name: string;
			};
			qty: string;
			variant_id: string;
			unit_id: number;
			unit: {
				id: number;
				name: string;
			};
		}[];
		deliveryArea: {
			id: number;
			area: string;
			charge: string;
		}[];
		courier: {
			id: number;
			name: string;
			code: string;
			charge: string;
		}[];
		cities: {
			id: number;
			name: string;
			code: string;
		}[];
	};
	default_courier: null;
	areas: {
		id: number;
		area: string;
		charge: string;
	}[];
};
