import { iPagination } from '@/types';

export type iDropShipperProduct = {
	id: number;
	category_id: number;
	subcategory_id: number;
	brand_id: number;
	user_id: number;
	slug: string;
	name: string;
	short_description: string;
	long_description: string;
	selling_price: string;
	original_price: string;
	qty: string;
	image: string;
	status: string;
	meta_title: null;
	meta_keyword: null;
	meta_description: null;
	tags: null;
	commision_type: null;
	request: null;
	user_type: null;
	discount_type: string;
	discount_rate: string;
	rejected_details: null;
	created_at: string;
	updated_at: string;
	deleted_at: null;
	variants: null;
	selling_type: string;
	selling_details: null;
	advance_payment: number;
	single_advance_payment_type: string;
	is_connect_bulk_single: string;
	specifications: string;
	uniqid: string;
	sku: string;
	distributor_price: null;
	alert_qty: number;
	supplier_id: number;
	warehouse_id: number;
	exp_date: string;
	barcode: null;
	warranty: string;
	is_feature: number;
	is_affiliate: number;
	discount_price: string;
	vendor_id: number;
	pre_order: string;
	discount_percentage: string;
	product_type: string;
	wc_product_id: null;
	tenant_id: string;
	tenant_domain: string;
	tenant_name: string;
	tenant_type: string;
	tenant_email: string;
	tenant_owner: string;
	tenant_phone: null;
};

export type iDropShipperProductResponse = {
	status: number;
	product: iPagination<iDropShipperProduct>;
};
