import { Contact, Message } from './chat';

export const contacts: Contact[] = [
	{
		id: '1',
		name: 'Jacquenetta Slowgrave',
		initials: 'JS',
		avatarColor: 'from-pink-300 to-purple-400',
		lastMessage: 'Great! Looking forwar...',
		time: '10 minutes',
		unreadCount: 8,
		checkType: 'read',
	},
	{
		id: '2',
		name: 'Nickola Peever',
		initials: 'NP',
		avatarColor: 'from-blue-300 to-indigo-400',
		lastMessage: "Sounds perfect! I've be...",
		time: '40 minutes',
		unreadCount: 2,
		checkType: 'read',
	},
	{
		id: '3',
		name: 'Farand Hume',
		initials: 'FH',
		avatarColor: 'from-yellow-300 to-orange-400',
		lastMessage: 'How about 7 PM at the new l...',
		time: 'Yesterday',
		checkType: 'read',
	},
	{
		id: '4',
		name: 'Ossie Peasey',
		initials: 'OP',
		avatarColor: 'from-green-300 to-teal-400',
		lastMessage: 'Hey Bonnie, yes, definitely! ...',
		time: '13 days',
		checkType: 'single',
	},
	{
		id: '5',
		name: 'Hall Negri',
		initials: 'HN',
		avatarColor: 'from-red-300 to-rose-400',
		lastMessage: "No worries at all! I'll grab a t...",
		time: '2 days',
		checkType: 'double',
	},
	{
		id: '6',
		name: 'Elyssa Segot',
		initials: 'ES',
		avatarColor: 'from-violet-300 to-purple-400',
		lastMessage: 'She just told me today.',
		time: 'Yesterday',
		checkType: 'read',
	},
	{
		id: '7',
		name: 'Gil Wilfing',
		initials: 'GW',
		avatarColor: 'from-emerald-300 to-blue-400',
		lastMessage: 'See you in 5 minutes!',
		time: '1 day',
		checkType: 'single',
	},
	{
		id: '8',
		name: 'Bab Cleaton',
		initials: 'BC',
		avatarColor: 'from-amber-200 to-amber-400',
		lastMessage: 'If it takes long you can mail',
		time: '3 hours',
		isOnline: true,
		checkType: 'double',
	},
	{
		id: '9',
		name: 'Janith Satch',
		initials: 'JS',
		avatarColor: 'from-green-100 to-emerald-400',
		lastMessage: "Absolutely! It's amazing...",
		time: '1 day',
		unreadCount: 2,
		checkType: 'read',
	},
	{
		id: '10',
		name: 'Biron Alison',
		initials: 'BA',
		avatarColor: 'from-pink-200 to-fuchsia-400',
		lastMessage: 'Yeah, she mentioned it last ...',
		time: '1 day',
		checkType: 'read',
	},
	{
		id: '11',
		name: 'Baily Younie',
		initials: 'BY',
		avatarColor: 'from-sky-200 to-cyan-400',
		lastMessage: 'Thanks, I appreciate it!...',
		time: 'Yesterday',
		checkType: 'read',
	},
];

export const messages: Message[] = [
	{
		id: '1',
		content:
			'I know how important this file is to you. You can trust me ;) I know how important this file is to you. You can trust me ;) know how important this file is to you. You can trust me ;)',
		time: '05:23 PM',
		isSent: false,
	},
];

export const activeContact = contacts.find((c) => c.id === '8')!;
